# Generated by Django 6.0.4 on 2026-04-25 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=255)),
                ("whatsapp", models.CharField(max_length=20)),
            ],
            options={
                "verbose_name": "Contact Info",
                "verbose_name_plural": "Contact Infos",
            },
        ),
        migrations.CreateModel(
            name="YogaType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "short_description",
                    models.TextField(help_text="A short summary for the main page."),
                ),
                (
                    "detailed_description",
                    models.TextField(help_text="Detailed description for the modal."),
                ),
                (
                    "image_url",
                    models.URLField(
                        blank=True,
                        help_text="URL to a high-quality image.",
                        max_length=500,
                        null=True,
                    ),
                ),
            ],
            options={
                "verbose_name": "Yoga Type",
                "verbose_name_plural": "Yoga Types",
            },
        ),
    ]
