# Generated by Django 6.0.4 on 2026-04-25 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Subhashita",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sanskrit_text",
                    models.TextField(help_text="The Sanskrit text of the Subhashita"),
                ),
                (
                    "english_meaning",
                    models.TextField(help_text="The English translation or meaning"),
                ),
            ],
            options={
                "verbose_name": "Subhashita",
                "verbose_name_plural": "Subhashitas",
            },
        ),
    ]
